import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Raleway } from "next/font/google";

const poppins = Poppins({ weight: "600", subsets: ["latin-ext"] });
const raleway = Raleway({ weight: "600", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
